services:
    frontend:
        build:
            context: .
            dockerfile: ./dev.Dockerfile
        tty: true
        ports:
#            - "3000:3000"
            - "3000"
        volumes:
            - ./:/app/
        networks:
            - vorti-network

    nginx:
        image: nginx:1.24.0
        ports:
            - "8000:80"
        volumes:
            - ./nginx/vorti.nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - vorti-network
networks:
    vorti-network:
        external: true
